
VALID_USERNAME = "analis"
VALID_PASSWORD = "password123"


[connections.gsheets]

spreadsheet = "DeteksiAnomaliHistory"
worksheet = "History"

type = "service_account"
project_id = "streamlit-app-466002"
private_key_id = "7614597603ce59aae6e6ed103c39d7452be552a5"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7dbO6FguKMy8z\nckguw1mbAqhFKkilE6vWzSihNx37Iw193JoDu8JJJefQf/f+PmGIPdslVJ7OpptD\nMaX4Fz9qc2TjQvPxW3xKy4JQQGqPau1QImw3cifMpmvyQ3CDrb1UQ3PDr3578Sat\nSStWbeRaw0/wlqIkTFThxqdEwZ8FqU66HyCXd9Vbg1TXQATzqAZfC8WrWHDCjMDT\nTJ219J96+OgVGQCfMT2dm13Pnz57HTXwbAfvHHnRc9SOJIsAbJOXlo84DDD6RrCQ\nB8k2FcPPNjfZdZZE3cRKvQdKOAbWc5dVEcLL46HDHxz7jWLntkjHXR6uxfNLiWmE\nOkMOxAXrAgMBAAECggEAEePhQ6Sf9E//NLM25VOaZRtDUNqAtVRjxWut8XjPoSyO\nuJDJmAqet5lo/rJ/yeFNMJHqrKzfPQyUa7y8wKkDUdbybWfx3PpkqcSzSpJjOQ20\n2T13w3DfEH5fde7uuXpmw7huP2IruYthrA78FlMFhI34Ppc5oSoxvZxWUU8DLKh6\nZsD8HBZwJFczbUr7GLQK2RvHYNSeaJdqeTkaoq/ZNXWCuA9FS37oFppSlRoxTAWv\nJmmqRA45WwjJG75M1kzCMUlIleh0mOCEl7LEQtCRjdxoId0FGvtxLRAf0pOIzwis\n9EM1jRANFHqAVKbSUjeetYzpEZTnAAqx0SAHuT92fQKBgQDpt2trAbPg6GY4nYZH\nxVNODeaNY5maWJkbO0MOBXd3TkRcNnox6NZWCsFHzD2otJO5QK/IZdWE5nM1VW2E\ngmv3G6RHs8WGMwd+O/xDYGXuaJMHOg/da03NplYYNMef3MQrD9VQqenYoZlzrIlr\nIbq647aqMSw/4ycIg3gYbcwBvwKBgQDNVT45S+eDnP34vS1+u+IsffrGgmYm2q59\n96sZcx09kZcMczLWtA4DXXYv/JiPExkv5ZZHHqyMx7brsvUs0c3BYZaPLZ/awXiP\n3b23LFLDUAElcAOXp7T/xP2vjSVxU/VKtb9Za4YRuFPLmihgbl+M8N2qWwPphSvD\nThUeUVnu1QKBgCz1cr1362Flc1yKuO0PgXHvbJ1gPokZaAJ8CO8mkA+sR6wxcpot\nPyX4Faw5FtdgPVaSof370PIq3piw4UtvR1OWxqhgZavmHxfidCmF3rXY+geW3Lxs\nSuA3kjI/3PLcpgPenNtShEB+/aTp2Nl5+JDBAz+EDA4SJU0W9UBFxsvDAoGBAIqx\nOF1lOtS4dwfLaG6BI+1fjsMFE1DNRy2I28ZN7gNHUtqy+TTy28BEIe+Z08ZYZRvo\nHNCfFHfm8lRURaznbe5gJ11AuQf+xJuQcHPIeYK5iHysI5ENU4GropswYIki5711\n8/DHYwCXG+qbjwhLpTjC/UbzQTo7nGrIVBVtZ6ydAoGBAN6kSou3p3u5rVM68c22\nq8BWXDbaK9gU8YPUNUFOYgmhZkoZuhfJAgXN5qh85CQ9DiJhhuckVVulza558UiX\n3UBitoeukquVediIrY3eeLT+f0kFjhHh1ykqiJVu0h92qVVm+7gYBuqhMb2MnJPe\nAsE4/78QcmjdxAul2jEMUeP3\n-----END PRIVATE KEY-----"""
client_email = "streamlit-history-writer@streamlit-app-466002.iam.gserviceaccount.com"
client_id = "116453546673753701181"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-history-writer%40streamlit-app-466002.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
